echo off
echo                        ------------------------------ 	
echo                        UPTOWN AUTOMATION SYSTEMS, INC
echo                        ------------------------------ 	
echo ÿ
echo To install the UPTOWN program, put the floppy disk in drive A: or B: and type 
echo ÿ
echo a:[Enter]
echo install[Enter]                
echo                               --OR--
echo b:[Enter]
echo install[Enter]
echo ÿ
echo After testing that your computer will run the program, it will be
echo installed in a directory named \MIX on the disk drive you select.
echo To run the Uptown Automation program, type MIX.
echo ÿ
echo To run the Uptown Automation demo, type DEMO.
echo ÿ
echo Required hardware:
echo ÿ
echo EGA, VGAm or MCGA Graphics adapter and a color or monochrome monitor.
echo 450k main system memory (RAM)
echo hard disk
echo ÿ
