echo off
echo                        ------------------------------ 	
echo                        UPTOWN AUTOMATION SYSTEMS, INC
echo                        ------------------------------ 	
echo ÿ
echo To install the UPTOWN program from a floppy disk, put it in drive A: or B: and type 
echo ÿ
echo a:[Enter]
echo install[Enter]                
echo                               --OR--
echo b:[Enter]
echo install[Enter]
echo
echo To install from a single self-extracting file, copy it to a temporary directory,
echo change to that directory, and type
echo
echo install[Enter]
echo ÿ
echo After testing that your computer will run the program, it will be
echo installed in a directory named \MIX on the disk drive you select.
echo To run the Uptown Automation program, type MIX.
echo To run the Uptown Automation demo, type DEMO.
echo ÿ
echo Required hardware:
echo EGA, VGAm or MCGA Graphics adapter and a color or monochrome monitor.
echo 640k main system memory (RAM), hard disk drive
echo ÿ
